<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwlxB3x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwlxB3x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwlxB3x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAwlxB3x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAwlxB3x\App_KernelDevDebugContainer([
    'container.build_hash' => 'AwlxB3x',
    'container.build_id' => 'a6499823',
    'container.build_time' => 1659128334,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwlxB3x');
